"""
Django settings for kora_control project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def _load_local_env():
    env_path = BASE_DIR / '.env'
    env_example_path = BASE_DIR / '.env.example'
    candidate_paths = [env_path, env_example_path]

    try:
        from dotenv import load_dotenv

        for path in candidate_paths:
            if path.exists():
                load_dotenv(path, override=False)
                break
        return
    except ImportError:
        pass

    for path in candidate_paths:
        if not path.exists():
            continue

        try:
            with path.open('r', encoding='utf-8') as env_file:
                for line in env_file:
                    line = line.strip()
                    if not line or line.startswith('#') or '=' not in line:
                        continue
                    key, value = line.split('=', 1)
                    key = key.strip()
                    value = value.strip().strip('"').strip("'")
                    if key and key not in os.environ:
                        os.environ[key] = value
            break
        except OSError:
            continue


_load_local_env()


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', '')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'True').lower() == 'true'

ALLOWED_HOSTS = ['127.0.0.1', 'localhost']
if DEBUG:
    # Accept LAN/dev hostnames in local development.
    ALLOWED_HOSTS += ['*']

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Database configuration
DB_ENGINE = os.environ.get('DB_ENGINE', '').strip().lower()
DB_NAME = os.environ.get('DB_NAME', 'kora_db').strip()
DB_USER = os.environ.get('DB_USER', 'kora_user').strip()
DB_PASSWORD = os.environ.get('DB_PASSWORD', '').strip()
DB_HOST = os.environ.get('DB_HOST', 'localhost').strip()
DB_PORT = os.environ.get('DB_PORT', '5432').strip()

if not DB_ENGINE:
    DB_ENGINE = 'sqlite' if DEBUG and not os.environ.get('DB_NAME') else 'postgresql'


# Application definition

INSTALLED_APPS = [
    'unfold',
    'unfold.contrib.filters',
    'unfold.contrib.forms',
    'unfold.contrib.import_export',
    'unfold.contrib.guardian',
    'unfold.contrib.simple_history',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
    'drf_spectacular',
    'django_apscheduler',
    'core',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'core.middleware.DisableCSRFForAPIMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'kora_control.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'kora_control.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

if DB_ENGINE in ('sqlite', 'sqlite3'):
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': DB_NAME,
            'USER': DB_USER,
            'PASSWORD': DB_PASSWORD,
            'HOST': DB_HOST,
            'PORT': DB_PORT,
            'OPTIONS': {
                'options': '-c search_path=kora'
            },
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 4,
        },
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Custom User Model
AUTH_USER_MODEL = 'core.User'

# Next.js app (admin "View on site" / sidebar portal links)
FRONTEND_BASE_URL = os.environ.get("FRONTEND_BASE_URL", "http://localhost:3000").rstrip("/")

# Google OAuth
GOOGLE_CLIENT_ID = os.environ.get("GOOGLE_CLIENT_ID", "").strip()
GOOGLE_CLIENT_SECRET = os.environ.get("GOOGLE_CLIENT_SECRET", "").strip()
GOOGLE_REDIRECT_URI = os.environ.get("GOOGLE_REDIRECT_URI", "postmessage").strip()

# Chapa (optional in DEBUG without key — billing uses mock redirect; set for production)
CHAPA_SECRET_KEY = os.environ.get("CHAPA_SECRET_KEY", "").strip()
CHAPA_CURRENCY = os.environ.get("CHAPA_CURRENCY", "ETB")
CHAPA_TIMEOUT_SECONDS = int(os.environ.get("CHAPA_TIMEOUT_SECONDS", "20"))

# CORS Configuration
# Supports dev (localhost:3000) and production (set FRONTEND_BASE_URL)
_frontend_base_url = os.environ.get("FRONTEND_BASE_URL", "http://localhost:3000").rstrip("/")
_frontend_url_https = _frontend_base_url.replace("http://", "https://")

CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://localhost:3001",
    "http://127.0.0.1:3000",
    "http://127.0.0.1:3001",
]

# Add frontend URL from env if not localhost
if DEBUG and _frontend_base_url not in CORS_ALLOWED_ORIGINS:
    CORS_ALLOWED_ORIGINS.append(_frontend_base_url)
    if _frontend_url_https not in CORS_ALLOWED_ORIGINS:
        CORS_ALLOWED_ORIGINS.append(_frontend_url_https)

CSRF_TRUSTED_ORIGINS = CORS_ALLOWED_ORIGINS.copy()

# Allow local network frontend origins during development (e.g. http://192.168.x.x:3000).
# Also allow Flutter web dev server on any port (commonly 5173, 8080, or random high ports).
CORS_ALLOWED_ORIGIN_REGEXES = [
    r"^https?://localhost:\d{1,5}$",
    r"^https?://127\.0\.0\.1:\d{1,5}$",
    r"^https?://\d{1,3}(?:\.\d{1,3}){3}:\d{1,5}$",
] if DEBUG else []

# Allow credentials (like JWT headers)
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_ALL_ORIGINS = False

# REST Framework Configuration
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
}

CHAT_ALLOWED_UPLOAD_MIME_TYPES = [
    'image/png',
    'image/jpeg',
    'application/pdf',
    'text/plain',
    'text/csv',
]
CHAT_MAX_UPLOAD_BYTES = 10 * 1024 * 1024

UNFOLD = {
    "SITE_TITLE": "Kora Control",
    "SITE_HEADER": "Kora Control Administration",
    "SITE_URL": "/",
    "SHOW_HISTORY": True,
    "SHOW_VIEW_ON_SITE": True,
    "SITE_DROPDOWN": [],
    "STYLES": [
        "https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200",
        f"/{STATIC_URL.strip('/')}/core/css/admin-overrides.css",
    ],
    "COLORS": {
        "primary": {
            "50": "250 250 250",
            "100": "244 244 245",
            "200": "228 228 231",
            "300": "212 212 216",
            "400": "161 161 170",
            "500": "113 113 122",
            "600": "82 82 91",
            "700": "63 63 70",
            "800": "39 39 42",
            "900": "24 24 27",
            "950": "9 9 11",
        },
    },
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": True,
        "navigation": [
            {
                "title": "Authentication",
                "separator": True,
                "items": [
                    {
                        "title": "Users",
                        "icon": "person",
                        "link": "admin:core_user_changelist",
                    },
                ],
            },
            {
                "title": "Plant Infrastructure",
                "separator": True,
                "items": [
                    {
                        "title": "Plant areas",
                        "icon": "factory",
                        "link": "admin:core_plantarea_changelist",
                    },
                    {
                        "title": "Plant equipments",
                        "icon": "precision_manufacturing",
                        "link": "admin:core_plantequipment_changelist",
                    },
                ],
            },
            {
                "title": "Industrial Engine",
                "separator": True,
                "items": [
                    {
                        "title": "Tags",
                        "icon": "label",
                        "link": "admin:core_tag_changelist",
                    },
                    {
                        "title": "Dashboard visuals",
                        "icon": "widgets",
                        "link": "admin:core_dashboardvisualization_changelist",
                    },
                    {
                        "title": "Tag Logs",
                        "icon": "history",
                        "link": "admin:core_taglog_changelist",
                    },
                    {
                        "title": "Trend annotations",
                        "icon": "edit_note",
                        "link": "admin:core_trendannotation_changelist",
                    },
                ],
            },
            {
                "title": "Alarms & Notifications",
                "separator": True,
                "items": [
                    {
                        "title": "Alarm rules",
                        "icon": "settings_alert",
                        "link": "admin:core_alarmrule_changelist",
                    },
                    {
                        "title": "Alarm events",
                        "icon": "notifications_active",
                        "link": "admin:core_alarmevent_changelist",
                    },
                    {
                        "title": "In-app notifications",
                        "icon": "notifications",
                        "link": "admin:core_inappnotification_changelist",
                    },
                    {
                        "title": "Subscriptions",
                        "icon": "mark_email_read",
                        "link": "admin:core_notificationsubscription_changelist",
                    },
                ],
            },
            {
                "title": "Operations & AI",
                "separator": True,
                "items": [
                    {
                        "title": "Operator Journal",
                        "icon": "auto_stories",
                        "link": "admin:core_operatorjournalentry_changelist",
                    },
                    {
                        "title": "AI Analysis",
                        "icon": "insights",
                        "link": "admin:core_aianalysis_changelist",
                    },
                ],
            },
            {
                "title": "Billing & Payments",
                "separator": True,
                "items": [
                    {
                        "title": "Bills",
                        "icon": "receipt_long",
                        "link": "admin:core_bill_changelist",
                    },
                    {
                        "title": "Transactions",
                        "icon": "payments",
                        "link": "admin:core_paymenttransaction_changelist",
                    },
                ],
            },
            {
                "title": "Support",
                "separator": True,
                "items": [
                    {
                        "title": "Complaints",
                        "icon": "feedback",
                        "link": "admin:core_complaint_changelist",
                    },
                ],
            },
        ],
    },
}

# SCADA Telemetry Deletion/Retention Settings
TAGLOG_RETENTION_DAYS = 30

