"""
Django settings for kora_control project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def _load_local_env():
    env_path = BASE_DIR / '.env'
    env_example_path = BASE_DIR / '.env.example'
    candidate_paths = [env_path, env_example_path]

    try:
        from dotenv import load_dotenv

        for path in candidate_paths:
            if path.exists():
                load_dotenv(path, override=False)
                break
        return
    except ImportError:
        pass

    for path in candidate_paths:
        if not path.exists():
            continue

        try:
            with path.open('r', encoding='utf-8') as env_file:
                for line in env_file:
                    line = line.strip()
                    if not line or line.startswith('#') or '=' not in line:
                        continue
                    key, value = line.split('=', 1)
                    key = key.strip()
                    value = value.strip().strip('"').strip("'")
                    if key and key not in os.environ:
                        os.environ[key] = value
            break
        except OSError:
            continue


_load_local_env()


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-144u@t^3rm99itul8org=5daox4=twjzbyzsrn_kkt5p-ufkb1'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['127.0.0.1', 'localhost']
if DEBUG:
    # Accept LAN/dev hostnames in local development.
    ALLOWED_HOSTS += ['*']

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Application definition

INSTALLED_APPS = [
    'unfold',
    'unfold.contrib.filters',
    'unfold.contrib.forms',
    'unfold.contrib.import_export',
    'unfold.contrib.guardian',
    'unfold.contrib.simple_history',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
    'drf_spectacular',
    'core',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'kora_control.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'kora_control.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'kora_db',
        'USER': 'kora_user',
        'PASSWORD': 'kora_password123',
        'HOST': 'localhost',
        'PORT': '5432',
        'OPTIONS': {
            'options': '-c search_path=kora'
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Custom User Model
AUTH_USER_MODEL = 'core.User'

# CORS Configuration
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://localhost:3001",
    "http://127.0.0.1:3000",
    "http://127.0.0.1:3001",
]

# Allow local network frontend origins during development (e.g. http://192.168.x.x:3000).
CORS_ALLOWED_ORIGIN_REGEXES = [
    r"^https?://localhost:30\d{2}$",
    r"^https?://127\.0\.0\.1:30\d{2}$",
    r"^https?://\d{1,3}(?:\.\d{1,3}){3}:30\d{2}$",
]

# Allow credentials (like JWT headers)
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_ALL_ORIGINS = False # Set to false since we are using explicit origins

# REST Framework Configuration
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
}

CHAT_ALLOWED_UPLOAD_MIME_TYPES = [
    'image/png',
    'image/jpeg',
    'application/pdf',
    'text/plain',
    'text/csv',
]
CHAT_MAX_UPLOAD_BYTES = 10 * 1024 * 1024

UNFOLD = {
    "SITE_TITLE": "Kora Control",
    "SITE_HEADER": "Kora Control Administration",
    "SITE_URL": "/",
    "SHOW_HISTORY": True,
    "SHOW_VIEW_ON_SITE": True,
    "STYLES": [
        "https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200",
        f"/{STATIC_URL.strip('/')}/core/css/admin-overrides.css",
    ],
    "COLORS": {
        "primary": {
            "50": "250 250 250",
            "100": "244 244 245",
            "200": "228 228 231",
            "300": "212 212 216",
            "400": "161 161 170",
            "500": "113 113 122",
            "600": "82 82 91",
            "700": "63 63 70",
            "800": "39 39 42",
            "900": "24 24 27",
            "950": "9 9 11",
        },
    },
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": True,
        "navigation": [
            {
                "title": "Authentication",
                "separator": True,
                "items": [
                    {
                        "title": "Users",
                        "icon": "person",
                        "link": "admin:core_user_changelist",
                    },
                ],
            },
            {
                "title": "Kora Engine",
                "separator": True,
                "items": [
                    {
                        "title": "Tags",
                        "icon": "label",
                        "link": "admin:core_tag_changelist",
                    },
                    {
                        "title": "Tag Logs",
                        "icon": "history",
                        "link": "admin:core_taglog_changelist",
                    },
                    {
                        "title": "AI Analysis",
                        "icon": "insights",
                        "link": "admin:core_aianalysis_changelist",
                    },
                ],
            },
            {
                "title": "Billing & Payments",
                "separator": True,
                "items": [
                    {
                        "title": "Bills",
                        "icon": "receipt_long",
                        "link": "admin:core_bill_changelist",
                    },
                    {
                        "title": "Transactions",
                        "icon": "payments",
                        "link": "admin:core_paymenttransaction_changelist",
                    },
                ],
            },
            {
                "title": "Support",
                "separator": True,
                "items": [
                    {
                        "title": "Complaints",
                        "icon": "feedback",
                        "link": "admin:core_complaint_changelist",
                    },
                ],
            },
        ],
    },
}
