# Generated by Django 6.0.4 on 2026-05-11 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_aianalysis_id_alter_bill_id_alter_complaint_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardVisualization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('widget_type', models.CharField(choices=[('tank', 'Animated tank'), ('gauge', 'Circular gauge'), ('status', 'Neon status'), ('trend', '60s trend chart')], max_length=16)),
                ('title', models.CharField(blank=True, help_text='Leave blank to use tag name.', max_length=120)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('scale_min', models.FloatField(default=0)),
                ('scale_max', models.FloatField(default=100, help_text='Used for gauge/tank filling and thresholds context.')),
                ('warning_high', models.FloatField(blank=True, null=True)),
                ('alarm_high', models.FloatField(blank=True, null=True)),
                ('warning_low', models.FloatField(blank=True, null=True)),
                ('alarm_low', models.FloatField(blank=True, null=True)),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_widgets', to='core.tag')),
            ],
            options={
                'ordering': ('sort_order', 'id'),
            },
        ),
    ]
