# Generated by Django 6.0.4 on 2026-05-20 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_plant_journal_notifications_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='billing_rate',
            field=models.DecimalField(decimal_places=2, default=1.5, help_text='Rate per unit (e.g. per cubic meter).', max_digits=6),
        ),
        migrations.AddField(
            model_name='user',
            name='meter_tag',
            field=models.ForeignKey(blank=True, help_text="SCADA Tag representing the consumer's water meter.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='core.tag'),
        ),
    ]
