# Generated by Django 6.0.4 on 2026-05-23 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_user_billing_rate_user_meter_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='face_encoding',
            field=models.JSONField(blank=True, help_text='Auto-generated array from profile_photo.', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(blank=True, help_text='Upload to auto-generate biometric encoding.', null=True, upload_to='profiles/'),
        ),
    ]
