# Generated by Django 6.0.5 on 2026-05-27 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_user_face_encoding_user_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='retention_days',
            field=models.PositiveIntegerField(blank=True, help_text="Custom retention period in days for this tag's logs. If blank, global default applies.", null=True),
        ),
    ]
