# Generated by Django 6.0.4 on 2026-06-02 03:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_equipmenthealth_maintenancetask_processsetpoint_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIFinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finding_type', models.CharField(choices=[('anomaly', 'Anomaly'), ('prediction', 'Prediction'), ('prioritization', 'Prioritization'), ('root_cause', 'Root Cause'), ('trend_abnormality', 'Trend Abnormality')], db_index=True, max_length=20)),
                ('result_json', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('alarm_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_findings', to='core.alarmevent')),
                ('tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_findings', to='core.tag')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='OperatorActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('control', 'Control'), ('setpoint', 'Setpoint'), ('alarm', 'Alarm'), ('override', 'Override')], max_length=20)),
                ('description', models.TextField()),
                ('old_value', models.CharField(blank=True, max_length=100)),
                ('new_value', models.CharField(blank=True, max_length=100)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('target_tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_logs', to='core.tag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
